dominique_blog:
    resource: "@DominiqueBlogBundle/Resources/config/routing.yml"
    prefix:   /blog

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

blog:
    resource: "@DominiqueBlogBundle/Controller/"
    type:     annotation